language: python
python: 3.5

env:
    - TOXENV=flake8
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36

matrix:
    fast_finish: true

    include:
        - python: nightly
          env: TOXENV=py37
        - python: pypy-5.4
          env: TOXENV=pypy_54
        - python: pypy3.3-5.2-alpha1
          env: TOXENV=pypy33

    allow_failures:
        - env: TOXENV=py26
        - env: TOXENV=pypy_54
        - env: TOXENV=pypy33
        - python: nightly

install:
    - pip install tox coveralls codecov

script:
    - tox

after_success:
    - codecov

notifications:
    email: false
