language: python
python: 3.5

env:
    - TOXENV=flake8
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3

matrix:
    fast_finish: true

    include:
        - python: "nightly"
          env: TOXENV=py36

    allow_failures:
        - python: "nightly"

install:
    - pip install tox coveralls

script:
    - tox

after_success:
    - coveralls
    - bash <(curl -s https://codecov.io/bash)
