language: python
python: 3.5

env:
    - TOXENV=flake8
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3

matrix:
    fast_finish: true

    include:
        - python: 3.6-dev
          env: TOXENV=py36
        - python: "nightly"
          env: TOXENV=py37

    allow_failures:
        - env: TOXENV=py26
        - env: TOXENV=py36
        - python: "nightly"

install:
    - pip install tox coveralls codecov

script:
    - tox

after_success:
    - codecov

notifications:
    email: false
