language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
matrix:
  include:
    - python: 3.5
      env:
      - TOX_ENV=py35
before_install:
  - sudo apt-get install pypy pypy3
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
