language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
  - "pypy2.7"
  - "pypy3.5"

install:
  - pip install pytest pytest-cov codecov

script:
  - pytest --cov=sqlparse

after_success:
    - codecov

notifications:
    email: false
