language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
install:
  - pip install pytest pytest-cov
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then mkdir -p py3k/ && cp -r tests/ py3k/ && 2to3 -w --no-diffs -n tests; fi
  - python setup.py install
script:
  - cd extras/
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then cd py3k/ && py.test -v tests/; fi
  # Change directory to avoid that the local sqlparse module is tested
  # instead of the installed one. This is relevant for the 2to3 version.
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then py.test -v --cov=sqlparse tests/; fi