language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
  - "pypy"
  - "pypy3"

matrix:
  fast_finish: true
  allow_failures:
    # see https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7

install:
  - pip install pytest pytest-cov codecov

script:
  - pytest --cov=sqlparse

after_success:
    - codecov

notifications:
    email: false
