language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - pip install -Uq pytest pytest-cov codecov
  - pytest --version

script:
  - pytest --cov=sqlparse

after_success:
    - codecov
